services:
  - type: web
    name: tutorialapi
    runtime: docker
    plan: free
    buildCommand: echo "Build step handled by Dockerfile"
    startCommand: java -jar app.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: tutorialapi-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: tutorialapi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: tutorialapi-db
          property: password
      - key: PORT
        value: "8080"

databases:
  - name: tutorialapi-db
    ipAllowList: []
