services:
  - type: web
    name: tutorialapi
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: tutorialapi-db
          property: connectionString

databases:
  - name: tutorialapi-db
    ipAllowList: []




